import = ["~/.config/alacritty/themes/themes/seashells.toml"]

[window]
padding = { x = 10, y = 10 }
dimensions = { columns = 125, lines = 35 }

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }

[colors]
draw_bold_text_with_bright_colors = true

[shell]
program = "/bin/zsh"

[keyboard]
bindings = [{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" }]
